language: go

before_install:
  - go get -u github.com/marthjod/gocart/...
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/dominikh/go-tools/staticcheck

script:
  - make vet
  - make lint
  - make staticcheck
  - make test
